import bcrypt from 'bcryptjs';
import { run, query } from '../db/database';
import { WeatherEvent, DataSource } from '../types';
import { TrustEngineService } from '../services/trustEngine';
import { DeduplicationService } from '../services/deduplicator';

export async function seedDatabase() {
  const existingUsers = await query(`SELECT COUNT(*) as count FROM users`);
  if (existingUsers[0]?.count > 0) {
    console.log('[Seed] Database already seeded. Skipping.');
    return;
  }

  console.log('[Seed] Seeding database with synthetic Indian weather intelligence data...');

  // 1. Seed Users
  const adminPass = await bcrypt.hash('Admin@1234', 10);
  const analystPass = await bcrypt.hash('Analyst@1234', 10);

  await run(`
    INSERT INTO users (id, email, password_hash, full_name, role, created_at)
    VALUES 
    ('usr_super_1', 'admin@weathervani.gov.in', ?, 'National Control Room Admin', 'SUPER_ADMIN', ?),
    ('usr_analyst_1', 'analyst@weathervani.gov.in', ?, 'Dr. Rajesh Sharma (Senior Meteorologist)', 'ANALYST', ?)
  `, [adminPass, new Date().toISOString(), analystPass, new Date().toISOString()]);

  // 2. Seed Data Sources
  const now = new Date().toISOString();
  await run(`
    INSERT INTO sources (id, name, source_type, endpoint_url, polling_interval_sec, is_active, reliability_score, total_reports_fetched, created_at)
    VALUES
    ('src_imd_api', 'India Meteorological Department (IMD) Open API', 'GOVERNMENT', 'https://mausam.imd.gov.in/api/v1/warnings', 300, 1, 98.0, 1420, ?),
    ('src_cwc_rss', 'Central Water Commission (CWC) Flood Alert RSS', 'GOVERNMENT', 'https://ffs.cwc.gov.in/rss/flood-bulletin', 600, 1, 95.0, 890, ?),
    ('src_twitter_feed', 'Authorized Twitter/X Weather Hashtag Monitor', 'SOCIAL_MEDIA', 'https://api.twitter.com/2/tweets/search/recent', 120, 1, 68.0, 4500, ?),
    ('src_open_meteo', 'Open-Meteo Global Weather API', 'PUBLIC_API', 'https://api.open-meteo.com/v1/forecast', 900, 1, 90.0, 2300, ?),
    ('src_citizen_portal', 'WeatherVani Citizen Reporting Portal', 'CITIZEN_REPORT', 'https://weathervani.gov.in/citizen/submit', 0, 1, 62.0, 310, ?)
  `, [now, now, now, now, now]);

  // 3. Seed Hashtags
  const hashtags = ['#IMD', '#Weather', '#Rain', '#HeavyRain', '#Thunderstorm', '#Flood', '#Cyclone', '#Heatwave', '#Storm', '#Lightning', '#Fog', '#DustStorm'];
  for (const tag of hashtags) {
    await run(`INSERT OR IGNORE INTO hashtags (id, tag, is_active, added_by, created_at) VALUES (?, ?, 1, 'System Admin', ?)`, [
      `ht_${tag.replace('#', '')}`,
      tag,
      now,
    ]);
  }

  // 4. Seed Weather Events across India
  const seedEvents: Partial<WeatherEvent>[] = [
    {
      event_id: 'evt_ap_visakhapatnam_01',
      source_id: 'src_imd_api',
      source_type: 'GOVERNMENT',
      source_url: 'https://mausam.imd.gov.in/bulletin/visakhapatnam',
      author_name: 'IMD Cyclone Warning Centre Visakhapatnam',
      timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(), // 2 hrs ago
      raw_text: 'Deep depression over Westcentral Bay of Bengal intensified into Severe Cyclonic Storm. Landfall expected near Visakhapatnam coast with wind speeds reaching 90-110 kmph accompanied by extremely heavy rainfall.',
      normalized_text: 'deep depression over westcentral bay of bengal intensified into severe cyclonic storm. landfall expected near visakhapatnam coast with wind speeds reaching 90-110 kmph accompanied by extremely heavy rainfall.',
      event_category: 'CYCLONE',
      event_subcategory: 'severe_cyclone',
      severity: 0.95,
      country: 'India',
      state: 'Andhra Pradesh',
      district: 'Visakhapatnam',
      city: 'Visakhapatnam',
      latitude: 17.6868,
      longitude: 83.2185,
      location_confidence: 0.98,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=800',
      hashtags: ['#CycloneAlert', '#Visakhapatnam', '#IMDRedAlert', '#BayOfBengal'],
      weather_values: { rainfall_mm: 185.0, temperature_c: 26.5, wind_speed_kmh: 105.0, pressure_hpa: 982.0 },
      verification_status: 'VERIFIED',
      verification_score: 96,
      trust_score: 96,
      ai_confidence: 0.95,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_mh_mumbai_01',
      source_id: 'src_twitter_feed',
      source_type: 'SOCIAL_MEDIA',
      source_url: 'https://twitter.com/mumbai_weather/status/10293849',
      author_name: 'MumbaiWeatherWatch',
      timestamp: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
      raw_text: 'Incessant torrential monsoon rains in Dadar and Hindmata causing severe waterlogging. Tracks submerged at Kurla station. #MumbaiRains #HeavyRain',
      normalized_text: 'incessant torrential monsoon rains in dadar and hindmata causing severe waterlogging. tracks submerged at kurla station.',
      event_category: 'FLOOD',
      event_subcategory: 'waterlogging',
      severity: 0.82,
      country: 'India',
      state: 'Maharashtra',
      district: 'Mumbai',
      city: 'Mumbai',
      latitude: 19.0760,
      longitude: 72.8777,
      location_confidence: 0.92,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800',
      hashtags: ['#MumbaiRains', '#HeavyRain', '#Flood', '#Waterlogging'],
      weather_values: { rainfall_mm: 142.0, temperature_c: 27.2, wind_speed_kmh: 42.0, humidity_percent: 96 },
      verification_status: 'VERIFIED',
      verification_score: 88,
      trust_score: 88,
      ai_confidence: 0.90,
      duplicate_score: 0.1,
      is_duplicate: false,
    },
    {
      event_id: 'evt_ts_hyderabad_01',
      source_id: 'src_citizen_portal',
      source_type: 'CITIZEN_REPORT',
      source_url: 'https://weathervani.gov.in/report/cit_88392',
      author_name: 'Suresh Reddy (Citizen Observer)',
      timestamp: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
      raw_text: 'Sudden severe thunderstorm with heavy lightning and hail stones near Gachibowli, Hyderabad. Trees uprooted near bio-diversity park.',
      normalized_text: 'sudden severe thunderstorm with heavy lightning and hail stones near gachibowli, hyderabad. trees uprooted near bio-diversity park.',
      event_category: 'THUNDERSTORM',
      event_subcategory: 'hail_lightning',
      severity: 0.75,
      country: 'India',
      state: 'Telangana',
      district: 'Hyderabad',
      city: 'Hyderabad',
      latitude: 17.4401,
      longitude: 78.3489,
      location_confidence: 0.90,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1605727216801-e27ce1d0cc28?w=800',
      hashtags: ['#HyderabadRains', '#Thunderstorm', '#Lightning', '#Gachibowli'],
      weather_values: { rainfall_mm: 68.0, temperature_c: 24.0, wind_speed_kmh: 62.0 },
      verification_status: 'UNDER_REVIEW',
      verification_score: 72,
      trust_score: 72,
      ai_confidence: 0.88,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_tn_chennai_01',
      source_id: 'src_imd_api',
      source_type: 'GOVERNMENT',
      source_url: 'https://mausam.imd.gov.in/chennai',
      author_name: 'Regional Meteorological Centre Chennai',
      timestamp: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
      raw_text: 'Heavy to extremely heavy rainfall alert issued for coastal Tamil Nadu including Chennai, Tiruvallur, and Kanchipuram due to upper air cyclonic circulation.',
      normalized_text: 'heavy to extremely heavy rainfall alert issued for coastal tamil nadu including chennai, tiruvallur, and kanchipuram due to upper air cyclonic circulation.',
      event_category: 'HEAVY_RAINFALL',
      event_subcategory: 'monsoon_downpour',
      severity: 0.78,
      country: 'India',
      state: 'Tamil Nadu',
      district: 'Chennai',
      city: 'Chennai',
      latitude: 13.0827,
      longitude: 80.2707,
      location_confidence: 0.95,
      media_type: 'NONE',
      hashtags: ['#ChennaiRains', '#HeavyRain', '#NEMonsoon', '#RMC'],
      weather_values: { rainfall_mm: 110.0, temperature_c: 28.0, wind_speed_kmh: 38.0 },
      verification_status: 'VERIFIED',
      verification_score: 92,
      trust_score: 92,
      ai_confidence: 0.92,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_or_puri_01',
      source_id: 'src_cwc_rss',
      source_type: 'GOVERNMENT',
      source_url: 'https://ffs.cwc.gov.in/puri',
      author_name: 'Central Water Commission Odisha',
      timestamp: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
      raw_text: 'Mahanadi river water level crossed danger level at Naraj. Low-lying areas in Cuttack and Puri district alerted for high river inundation.',
      normalized_text: 'mahanadi river water level crossed danger level at naraj. low-lying areas in cuttack and puri district alerted for high river inundation.',
      event_category: 'FLASH_FLOOD',
      event_subcategory: 'riverine_flood',
      severity: 0.88,
      country: 'India',
      state: 'Odisha',
      district: 'Puri',
      city: 'Puri',
      latitude: 19.8135,
      longitude: 85.8312,
      location_confidence: 0.96,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800',
      hashtags: ['#OdishaFloods', '#Mahanadi', '#FloodAlert', '#Puri'],
      weather_values: { rainfall_mm: 160.0, temperature_c: 27.5 },
      verification_status: 'VERIFIED',
      verification_score: 95,
      trust_score: 95,
      ai_confidence: 0.94,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_kl_wayanad_01',
      source_id: 'src_imd_api',
      source_type: 'GOVERNMENT',
      source_url: 'https://mausam.imd.gov.in/wayanad',
      author_name: 'State Disaster Management Authority Kerala',
      timestamp: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
      raw_text: 'Red alert in Wayanad and Idukki districts for cloudburst and major landslides following 220mm continuous rain in 12 hours.',
      normalized_text: 'red alert in wayanad and idukki districts for cloudburst and major landslides following 220mm continuous rain in 12 hours.',
      event_category: 'LANDSLIDE',
      event_subcategory: 'landslide_cloudburst',
      severity: 0.92,
      country: 'India',
      state: 'Kerala',
      district: 'Wayanad',
      city: 'Kalpetta',
      latitude: 11.6103,
      longitude: 76.0828,
      location_confidence: 0.97,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      hashtags: ['#KeralaRains', '#Wayanad', '#LandslideAlert', '#RedAlert'],
      weather_values: { rainfall_mm: 220.0, temperature_c: 22.0, wind_speed_kmh: 50.0 },
      verification_status: 'VERIFIED',
      verification_score: 97,
      trust_score: 97,
      ai_confidence: 0.96,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_rj_churu_01',
      source_id: 'src_open_meteo',
      source_type: 'PUBLIC_API',
      source_url: 'https://open-meteo.com/churu',
      author_name: 'Rajasthan Weather Station Churu',
      timestamp: new Date(Date.now() - 3600 * 1000 * 30).toISOString(),
      raw_text: 'Extreme severe heatwave conditions in Churu and Bikaner districts with maximum temperature crossing 48.5°C accompanied by intense Loo winds.',
      normalized_text: 'extreme severe heatwave conditions in churu and bikaner districts with maximum temperature crossing 48.5°c accompanied by intense loo winds.',
      event_category: 'HEATWAVE',
      event_subcategory: 'extreme_heat',
      severity: 0.89,
      country: 'India',
      state: 'Rajasthan',
      district: 'Churu',
      city: 'Churu',
      latitude: 28.2900,
      longitude: 74.9700,
      location_confidence: 0.94,
      media_type: 'NONE',
      hashtags: ['#Heatwave', '#Rajasthan', '#Loo', '#ExtremeWeather'],
      weather_values: { temperature_c: 48.5, humidity_percent: 18, wind_speed_kmh: 35.0 },
      verification_status: 'VERIFIED',
      verification_score: 91,
      trust_score: 91,
      ai_confidence: 0.93,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_dl_delhi_01',
      source_id: 'src_twitter_feed',
      source_type: 'SOCIAL_MEDIA',
      source_url: 'https://twitter.com/delhi_weather/status/993821',
      author_name: 'CapitalWeatherTracker',
      timestamp: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
      raw_text: 'Blinding dust storm (Andhi) hits National Capital Region (NCR) reducing visibility below 100 meters followed by gusty winds.',
      normalized_text: 'blinding dust storm (andhi) hits national capital region (ncr) reducing visibility below 100 meters followed by gusty winds.',
      event_category: 'DUST_STORM',
      event_subcategory: 'andhi_squall',
      severity: 0.68,
      country: 'India',
      state: 'Delhi',
      district: 'New Delhi',
      city: 'New Delhi',
      latitude: 28.6139,
      longitude: 77.2090,
      location_confidence: 0.90,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800',
      hashtags: ['#DelhiDustStorm', '#Andhi', '#DelhiWeather', '#NCR'],
      weather_values: { temperature_c: 38.0, wind_speed_kmh: 70.0, humidity_percent: 30 },
      verification_status: 'VERIFIED',
      verification_score: 84,
      trust_score: 84,
      ai_confidence: 0.89,
      duplicate_score: 0.05,
      is_duplicate: false,
    },
    {
      event_id: 'evt_jk_srinagar_01',
      source_id: 'src_open_meteo',
      source_type: 'PUBLIC_API',
      source_url: 'https://open-meteo.com/srinagar',
      author_name: 'IMD Meteorological Centre Srinagar',
      timestamp: new Date(Date.now() - 3600 * 1000 * 14).toISOString(),
      raw_text: 'Dense fog and freezing cold wave conditions persist in Kashmir valley with sub-zero temperatures (-4.2°C) disrupting flight operations at Srinagar airport.',
      normalized_text: 'dense fog and freezing cold wave conditions persist in kashmir valley with sub-zero temperatures (-4.2°c) disrupting flight operations at srinagar airport.',
      event_category: 'FOG',
      event_subcategory: 'dense_fog_coldwave',
      severity: 0.72,
      country: 'India',
      state: 'Jammu & Kashmir',
      district: 'Srinagar',
      city: 'Srinagar',
      latitude: 34.0837,
      longitude: 74.7973,
      location_confidence: 0.95,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1486496146582-9ffcd0b2b2b7?w=800',
      hashtags: ['#KashmirCold', '#Srinagar', '#DenseFog', '#ColdWave'],
      weather_values: { temperature_c: -4.2, humidity_percent: 98, wind_speed_kmh: 8.0 },
      verification_status: 'VERIFIED',
      verification_score: 89,
      trust_score: 89,
      ai_confidence: 0.91,
      duplicate_score: 0.0,
      is_duplicate: false,
    },
    {
      event_id: 'evt_as_guwahati_01',
      source_id: 'src_cwc_rss',
      source_type: 'GOVERNMENT',
      source_url: 'https://ffs.cwc.gov.in/assam',
      author_name: 'Assam State Disaster Management Authority',
      timestamp: new Date(Date.now() - 3600 * 1000 * 36).toISOString(),
      raw_text: 'Brahmaputra river flowing above danger mark in 6 districts. Kaziranga national park inundated with flood waters.',
      normalized_text: 'brahmaputra river flowing above danger mark in 6 districts. kaziranga national park inundated with flood waters.',
      event_category: 'FLOOD',
      event_subcategory: 'monsoon_flooding',
      severity: 0.86,
      country: 'India',
      state: 'Assam',
      district: 'Kamrup Metropolitan',
      city: 'Guwahati',
      latitude: 26.1445,
      longitude: 91.7362,
      location_confidence: 0.96,
      media_type: 'IMAGE',
      media_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800',
      hashtags: ['#AssamFloods', '#Brahmaputra', '#Kaziranga', '#ASDMA'],
      weather_values: { rainfall_mm: 175.0, temperature_c: 26.0 },
      verification_status: 'VERIFIED',
      verification_score: 94,
      trust_score: 94,
      ai_confidence: 0.95,
      duplicate_score: 0.0,
      is_duplicate: false,
    }
  ];

  for (const ev of seedEvents) {
    await run(`
      INSERT OR IGNORE INTO weather_events (
        event_id, source_id, source_type, source_url, author_name, timestamp, ingestion_timestamp,
        raw_text, normalized_text, event_category, event_subcategory, severity, country, state, district,
        city, latitude, longitude, location_confidence, media_type, media_url, hashtags, weather_values,
        verification_status, verification_score, trust_score, ai_confidence, duplicate_score, is_duplicate,
        parent_event_id, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      ev.event_id, ev.source_id, ev.source_type, ev.source_url, ev.author_name, ev.timestamp, ev.timestamp,
      ev.raw_text, ev.normalized_text, ev.event_category, ev.event_subcategory, ev.severity, ev.country, ev.state,
      ev.district, ev.city, ev.latitude, ev.longitude, ev.location_confidence, ev.media_type, ev.media_url,
      JSON.stringify(ev.hashtags), JSON.stringify(ev.weather_values), ev.verification_status, ev.verification_score,
      ev.trust_score, ev.ai_confidence, ev.duplicate_score, ev.is_duplicate ? 1 : 0, ev.parent_event_id || null,
      ev.timestamp, ev.timestamp
    ]);
  }

  console.log('[Seed] Database successfully populated with initial Indian weather data.');
}
